pipeline {
    agent any

    stages {
        stage('Unit Test Backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '-v $HOME/.cache/go-build:/go/.cache/go-build -e GOCACHE=/go/.cache/go-build -e GOMODCACHE=/go/.cache/mod'
                }
            }
            steps {
                dir('bugtracker-backend/cmd/bugtracker') {
                      sh 'go test -V ./...'
                }
            }
        }
    }
}
