pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend/cmd/bugtracker') {
                      sh '''
                export GOCACHE=$(pwd)/.gocache
                export GOMODCACHE=$(pwd)/.gomodcache

                mkdir -p $GOCACHE
                mkdir -p $GOMODCACHE

                go mod tidy
                go test -v ./...
            '''
                }
            }
        }

        stage('Unit Test -Frontend'){
            agent{
                docker {
                    image 'node:20'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test 
                      '''
                }
            }
        }
    }
}
